//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadArchive
    {
        public string BBL { get; set; }
        public Nullable<int> TaxLienList { get; set; }
        public Nullable<int> TaxLienSold { get; set; }
        public Nullable<int> MortgageForeclosureLienLP { get; set; }
        public Nullable<int> TaxLienLP { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Operation { get; set; }
        public Nullable<int> LeadType { get; set; }
    }
}
