//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedScenario
    {
        public long ScenarioId { get; set; }
        public string ScenarioName { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateTimeSaved { get; set; }
        public string Description { get; set; }
        public string ZipCode { get; set; }
        public string BuildingClassCodes { get; set; }
        public string Counties { get; set; }
        public string Vacant { get; set; }
        public string MailingAddressActive { get; set; }
        public string Violations { get; set; }
        public string Cities { get; set; }
        public string Neighborhoods { get; set; }
        public string States { get; set; }
        public string LienTypes { get; set; }
        public string LeadGrades { get; set; }
        public string LTV { get; set; }
        public string Equity { get; set; }
        public string IsFannie { get; set; }
        public string IsFreddie { get; set; }
        public string UnbuiltArea { get; set; }
        public string Servicer { get; set; }
        public string Landmark { get; set; }
    }
}
