//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectListProperty
    {
        public long ListId { get; set; }
        public string BBL { get; set; }
    
        public virtual SavedList SavedList { get; set; }
    }
}
