//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGeneralLeadInfomation
    {
        public string BBLE { get; set; }
        public string TaxClass { get; set; }
        public Nullable<double> LotFrontage { get; set; }
        public Nullable<double> LotDepth { get; set; }
        public Nullable<double> LotArea { get; set; }
        public string BuildingClass { get; set; }
        public string BuildingClassDescription { get; set; }
        public Nullable<double> BuildingForntage { get; set; }
        public Nullable<double> BuildingDepth { get; set; }
        public Nullable<double> Stories { get; set; }
        public Nullable<double> NumberOfBuildingsOnLot { get; set; }
        public Nullable<double> BuildingGrossArea { get; set; }
        public Nullable<double> BuiltFAR { get; set; }
        public Nullable<double> MaxResidentialFAR { get; set; }
        public Nullable<double> YearBuilt { get; set; }
        public Nullable<double> Borough { get; set; }
        public string BoroughName { get; set; }
        public Nullable<double> Block { get; set; }
        public Nullable<double> Lot { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string ZipCode { get; set; }
        public string NeighborhoodName { get; set; }
        public string NTACode { get; set; }
        public string Zoning { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<decimal> East { get; set; }
        public Nullable<decimal> North { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<double> ResidentialUnits { get; set; }
        public int TaxLienList { get; set; }
        public int PoolA { get; set; }
        public Nullable<int> TaxLienLPs { get; set; }
        public Nullable<int> TaxLienActiveCases { get; set; }
        public Nullable<int> COSPresent { get; set; }
        public string FormattedAddress { get; set; }
        public string IsVacant { get; set; }
        public string IsMailingAddressActive { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ECBAmountDue { get; set; }
        public Nullable<int> ECBOpenTickets { get; set; }
    }
}
