//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DexiRequestType
    {
        public int RequestTypeId { get; set; }
        public string RobotId { get; set; }
    
        public virtual RequestType RequestType { get; set; }
    }
}
