//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage
    {
        public string BBL { get; set; }
        public string MortgageDocumentURI { get; set; }
        public string FHACaseNumber { get; set; }
        public string MortgageAmounts { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
