//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeOfProperyValue
    {
        public string BBL { get; set; }
        public string BuildingClassCode { get; set; }
        public string PrimaryZoning { get; set; }
        public Nullable<decimal> LotFrontage { get; set; }
        public Nullable<decimal> LotDepth { get; set; }
        public Nullable<decimal> LotSquareFootage { get; set; }
        public string LotShape { get; set; }
        public string LotType { get; set; }
        public string Proximity { get; set; }
        public Nullable<decimal> BuildingFrontage { get; set; }
        public Nullable<decimal> BuildingDepth { get; set; }
        public Nullable<int> NumberOfBuildings { get; set; }
        public string Style { get; set; }
        public string YearBuilt { get; set; }
        public string ExteriorCondition { get; set; }
        public Nullable<decimal> FinishedSquareFootage { get; set; }
        public Nullable<decimal> UnfinishedSquareFootage { get; set; }
        public Nullable<int> CommercialUnits { get; set; }
        public Nullable<decimal> CommercialSquareFootage { get; set; }
        public Nullable<int> ResidentialUnits { get; set; }
        public string GarageType { get; set; }
        public Nullable<decimal> GarageSquareFootage { get; set; }
        public string BasementGrade { get; set; }
        public Nullable<decimal> BasementSquareFootage { get; set; }
        public string BasementType { get; set; }
        public string ConstructionType { get; set; }
        public string ExteriorWall { get; set; }
        public Nullable<decimal> NumberOfStories { get; set; }
        public string StructureType { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> GrossSquareFootage { get; set; }
        public string CommercialOverlay { get; set; }
        public Nullable<decimal> LandFactorPerSqFtinDollars { get; set; }
        public Nullable<decimal> GrossResidentialSquareFootage { get; set; }
        public string LandType1 { get; set; }
        public Nullable<decimal> LandSize1 { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public string HotelClass { get; set; }
        public Nullable<int> NumberOfResidentialLots { get; set; }
        public Nullable<int> NumberOfCommercialLots { get; set; }
        public Nullable<decimal> GrossSquareFootageOfTheSuffix { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
