//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestType()
        {
            this.Requests = new HashSet<Request>();
            this.DataRequestLogs = new HashSet<DataRequestLog>();
        }
    
        public int RequestTypeId { get; set; }
        public string RequestTypeName { get; set; }
        public int MaxAttempts { get; set; }
        public int TimeDelayInMinute { get; set; }
        public Nullable<int> DaysToRefresh { get; set; }
        public Nullable<int> PriorityDaysToRefresh { get; set; }
    
        public virtual DexiRequestType DexiRequestType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataRequestLog> DataRequestLogs { get; set; }
    }
}
