//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NYCOURTSEntities : DbContext
    {
        public NYCOURTSEntities()
            : base("name=NYCOURTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Appearance> Appearances { get; set; }
        public virtual DbSet<Motion> Motions { get; set; }
        public virtual DbSet<vwAppearanceExpanded> vwAppearanceExpandeds { get; set; }
        public virtual DbSet<vwCaseExpanded> vwCaseExpandeds { get; set; }
        public virtual DbSet<vwMotionExpanded> vwMotionExpandeds { get; set; }
        public virtual DbSet<Attorney> Attorneys { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<GeneralData> GeneralDatas { get; set; }
        public virtual DbSet<vwAttorneyExpanded> vwAttorneyExpandeds { get; set; }
        public virtual DbSet<vwGeneralDataExpanded> vwGeneralDataExpandeds { get; set; }
        public virtual DbSet<RemarkData> RemarkDatas { get; set; }
    
        [DbFunction("NYCOURTSEntities", "tfnGetCaseUpdates")]
        public virtual IQueryable<tfnGetCaseUpdates_Result> tfnGetCaseUpdates(string countyId, string caseIndexNumber)
        {
            var countyIdParameter = countyId != null ?
                new ObjectParameter("CountyId", countyId) :
                new ObjectParameter("CountyId", typeof(string));
    
            var caseIndexNumberParameter = caseIndexNumber != null ?
                new ObjectParameter("CaseIndexNumber", caseIndexNumber) :
                new ObjectParameter("CaseIndexNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetCaseUpdates_Result>("[NYCOURTSEntities].[tfnGetCaseUpdates](@CountyId, @CaseIndexNumber)", countyIdParameter, caseIndexNumberParameter);
        }
    }
}
