//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NYCOURTSEntities : DbContext
    {
        public NYCOURTSEntities()
            : base("name=NYCOURTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appearance> Appearances { get; set; }
        public virtual DbSet<Attorney> Attorneys { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Motion> Motions { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<GeneralData> GeneralDatas { get; set; }
        public virtual DbSet<RemarkData> RemarkDatas { get; set; }
        public virtual DbSet<vwAppearanceExpanded> vwAppearanceExpandeds { get; set; }
        public virtual DbSet<vwAttorneyExpanded> vwAttorneyExpandeds { get; set; }
        public virtual DbSet<vwCaseExpanded> vwCaseExpandeds { get; set; }
        public virtual DbSet<vwMotionExpanded> vwMotionExpandeds { get; set; }
        public virtual DbSet<vwGeneralDataExpanded> vwGeneralDataExpandeds { get; set; }
    
        [DbFunction("NYCOURTSEntities", "tfnGetAllCasesForaProperty")]
        public virtual IQueryable<tfnGetAllCasesForaProperty_Result> tfnGetAllCasesForaProperty(string bBL)
        {
            var bBLParameter = bBL != null ?
                new ObjectParameter("BBL", bBL) :
                new ObjectParameter("BBL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetAllCasesForaProperty_Result>("[NYCOURTSEntities].[tfnGetAllCasesForaProperty](@BBL)", bBLParameter);
        }
    
        [DbFunction("NYCOURTSEntities", "tfnGetCaseColumnChanges")]
        public virtual IQueryable<tfnGetCaseColumnChanges_Result> tfnGetCaseColumnChanges(string tablename, string columnName, Nullable<System.DateTime> startDateTime, Nullable<System.DateTime> endDateTime)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("Tablename", tablename) :
                new ObjectParameter("Tablename", typeof(string));
    
            var columnNameParameter = columnName != null ?
                new ObjectParameter("ColumnName", columnName) :
                new ObjectParameter("ColumnName", typeof(string));
    
            var startDateTimeParameter = startDateTime.HasValue ?
                new ObjectParameter("StartDateTime", startDateTime) :
                new ObjectParameter("StartDateTime", typeof(System.DateTime));
    
            var endDateTimeParameter = endDateTime.HasValue ?
                new ObjectParameter("EndDateTime", endDateTime) :
                new ObjectParameter("EndDateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetCaseColumnChanges_Result>("[NYCOURTSEntities].[tfnGetCaseColumnChanges](@Tablename, @ColumnName, @StartDateTime, @EndDateTime)", tablenameParameter, columnNameParameter, startDateTimeParameter, endDateTimeParameter);
        }
    
        [DbFunction("NYCOURTSEntities", "tfnGetCaseUpdates")]
        public virtual IQueryable<tfnGetCaseUpdates_Result> tfnGetCaseUpdates(string countyId, string caseIndexNumber)
        {
            var countyIdParameter = countyId != null ?
                new ObjectParameter("CountyId", countyId) :
                new ObjectParameter("CountyId", typeof(string));
    
            var caseIndexNumberParameter = caseIndexNumber != null ?
                new ObjectParameter("CaseIndexNumber", caseIndexNumber) :
                new ObjectParameter("CaseIndexNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetCaseUpdates_Result>("[NYCOURTSEntities].[tfnGetCaseUpdates](@CountyId, @CaseIndexNumber)", countyIdParameter, caseIndexNumberParameter);
        }
    
        [DbFunction("NYCOURTSEntities", "tfnGetMortgageForeclosureCasesForaProperty")]
        public virtual IQueryable<tfnGetMortgageForeclosureCasesForaProperty_Result> tfnGetMortgageForeclosureCasesForaProperty(string bBL)
        {
            var bBLParameter = bBL != null ?
                new ObjectParameter("BBL", bBL) :
                new ObjectParameter("BBL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetMortgageForeclosureCasesForaProperty_Result>("[NYCOURTSEntities].[tfnGetMortgageForeclosureCasesForaProperty](@BBL)", bBLParameter);
        }
    
        [DbFunction("NYCOURTSEntities", "tfnGetNewMortgageForeclosureCases")]
        public virtual IQueryable<tfnGetNewMortgageForeclosureCases_Result> tfnGetNewMortgageForeclosureCases(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetNewMortgageForeclosureCases_Result>("[NYCOURTSEntities].[tfnGetNewMortgageForeclosureCases](@StartDate, @EndDate)", startDateParameter, endDateParameter);
        }
    
        [DbFunction("NYCOURTSEntities", "tfnGetMortgageForeclosureLPsForaProperty")]
        public virtual IQueryable<tfnGetMortgageForeclosureLPsForaProperty_Result> tfnGetMortgageForeclosureLPsForaProperty(string bBL, Nullable<System.DateTime> startDate)
        {
            var bBLParameter = bBL != null ?
                new ObjectParameter("BBL", bBL) :
                new ObjectParameter("BBL", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetMortgageForeclosureLPsForaProperty_Result>("[NYCOURTSEntities].[tfnGetMortgageForeclosureLPsForaProperty](@BBL, @StartDate)", bBLParameter, startDateParameter);
        }
    }
}
