//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarkData
    {
        public long RemarkId { get; set; }
        public string CountyId { get; set; }
        public string KeyValue { get; set; }
        public string Seq { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string LineNumber { get; set; }
        public string Remark { get; set; }
    }
}
