//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public string CountyId { get; set; }
        public string CaseIndexNumber { get; set; }
        public string SeqNumber { get; set; }
        public string PlaintiffDetailedName { get; set; }
        public string Plaintiff { get; set; }
        public string DefendantDetailedName { get; set; }
        public string Defendant { get; set; }
    }
}
