//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAppearanceExpanded
    {
        public string CountyId { get; set; }
        public string CaseIndexNumber { get; set; }
        public string MotionSeqNumber { get; set; }
        public string SeqNumber { get; set; }
        public Nullable<System.DateTime> AppearanceDate { get; set; }
        public string Series { get; set; }
        public string CourtPartsId { get; set; }
        public string CourtPart { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string AssignedJudgeId { get; set; }
        public string AssignedJudgeName { get; set; }
        public string CalendarMarkId { get; set; }
        public string ActionAtAppearance { get; set; }
        public string AppearanceType { get; set; }
        public string AppearanceTypeDescription { get; set; }
        public string Comments1 { get; set; }
        public string Comments2 { get; set; }
        public string ConferenceGroup { get; set; }
        public string Conferencebuilding { get; set; }
        public Nullable<System.DateTime> ConferenceNotePrintDate { get; set; }
        public string MotionPositionNumber { get; set; }
    }
}
