//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCaseExpanded
    {
        public string CountyId { get; set; }
        public string CaseIndexNumber { get; set; }
        public string CaseIndexNumberExternal { get; set; }
        public string SeqNumber { get; set; }
        public string CourtType { get; set; }
        public string CaseStatus { get; set; }
        public string PostDispositionIndicator { get; set; }
        public string CourtCalendarNumber { get; set; }
        public string PremliminaryConferenceIndicator { get; set; }
        public Nullable<int> NumberOfComments { get; set; }
        public string PreIASJHOId { get; set; }
        public string PreIASJHOName { get; set; }
        public string PreIASTAPId { get; set; }
        public string PreIASTAPName { get; set; }
        public string PlaintiffName { get; set; }
        public string DefendantName { get; set; }
        public string MunicipalityInvolvement { get; set; }
        public string CaseComplexity { get; set; }
        public Nullable<System.DateTime> RJIDispositionDeadlineDate { get; set; }
        public Nullable<System.DateTime> RJIPreNOIDeadlineDate { get; set; }
        public Nullable<System.DateTime> PostNOIDispositionDeadlineDate { get; set; }
        public Nullable<System.DateTime> DateRJIFiled { get; set; }
        public Nullable<System.DateTime> DateNOIFiled { get; set; }
        public Nullable<System.DateTime> TimeStampNOIEntered { get; set; }
        public Nullable<System.DateTime> DateIssueJoined { get; set; }
        public string JuryStatus1 { get; set; }
        public Nullable<System.DateTime> JuryStatusRequestDate1 { get; set; }
        public string JuryStatus2 { get; set; }
        public Nullable<System.DateTime> JuryStatusRequestDate2 { get; set; }
        public string JuryStatus3 { get; set; }
        public Nullable<System.DateTime> JuryStatusRequestDate3 { get; set; }
        public string ActionOrCaseTypeId { get; set; }
        public string ActionOrCaseType { get; set; }
        public string ActionOrCaseTypeDescription { get; set; }
        public string DamagesSought { get; set; }
        public string GeneralPreference { get; set; }
        public string SpecialPreference { get; set; }
        public Nullable<System.DateTime> CaseDispositionDate { get; set; }
        public string JoinedCasePreviousIndex { get; set; }
        public string JoinedCaseNextIndex { get; set; }
        public string RJITypeCode { get; set; }
        public string TypeOfRJI { get; set; }
        public Nullable<System.DateTime> DateOfRJI { get; set; }
        public string RJICourtPartId { get; set; }
        public string RJICourtPart { get; set; }
        public string CommentForOtherRJIType { get; set; }
        public Nullable<int> EstimatedTrialTime { get; set; }
        public Nullable<int> ActualTrialTime { get; set; }
        public string PropertySection { get; set; }
        public string PropertyBlock { get; set; }
        public string PropertyLot { get; set; }
        public string PropertySchoolDistrict { get; set; }
        public Nullable<double> AssessmentAmount { get; set; }
        public Nullable<double> AmountAwarded { get; set; }
        public string LandUse { get; set; }
        public string PreliminaryCalendarNumber { get; set; }
        public string IASCategoryId { get; set; }
        public string IASCategory { get; set; }
        public string IASJudgeId { get; set; }
        public string IASJudgeName { get; set; }
        public Nullable<System.DateTime> IASAssignmentDate { get; set; }
        public Nullable<System.DateTime> TimeStampLastIASInformationEntered { get; set; }
        public string PostDispositionActionJudgeId { get; set; }
        public string PostDispositionActionJudgeName { get; set; }
        public string PROSEIndicator { get; set; }
        public Nullable<int> AmountSuedFor { get; set; }
        public string BillOfParticularServed { get; set; }
        public Nullable<int> NumberOfTitleRecords { get; set; }
        public Nullable<int> NumberOfAttorneyRecords { get; set; }
        public Nullable<int> NumberOfCarrierRecords { get; set; }
        public Nullable<System.DateTime> DateRJIEntered { get; set; }
        public Nullable<System.DateTime> DateCertOfReadinessFiled { get; set; }
        public Nullable<System.DateTime> CertOfReadinessDueDate { get; set; }
        public Nullable<System.DateTime> NOIDueDate { get; set; }
        public Nullable<System.DateTime> LatestStatusConferenceSchdDate { get; set; }
        public Nullable<System.DateTime> LatestStatusConferenceHeldDate { get; set; }
        public Nullable<System.DateTime> LatestPreTrialConfSchdDate { get; set; }
        public Nullable<System.DateTime> LatestPreTrialConferenceHeldDate { get; set; }
        public Nullable<System.DateTime> LatestPreliminaryConferenceReqDate { get; set; }
        public Nullable<System.DateTime> LatestPreliminaryConferenceSchdDate { get; set; }
        public Nullable<System.DateTime> PreliminaryConferenceHeldDate { get; set; }
        public Nullable<System.DateTime> ComplianceConferenceSchdDate { get; set; }
        public Nullable<System.DateTime> ComplianceConferenceHeldDate { get; set; }
        public Nullable<System.DateTime> LastComplianceConferenceDate { get; set; }
        public string PrivateCaseIndicator { get; set; }
        public string IsEfiled { get; set; }
        public Nullable<System.DateTime> DateOfGoodService { get; set; }
        public Nullable<System.DateTime> DateForeclosureSettelementConfScheduled { get; set; }
        public Nullable<System.DateTime> DateForeclosureSettelementConfHeld { get; set; }
        public string Comment { get; set; }
    }
}
