//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGeneralDataExpanded
    {
        public string County { get; set; }
        public string CountyId { get; set; }
        public string KeyValue { get; set; }
        public string Seq { get; set; }
        public string EnteredCountyId { get; set; }
        public string EnteredCounty { get; set; }
        public Nullable<System.DateTime> DataEntryDateTime { get; set; }
        public string BookTypeId { get; set; }
        public string BookTypeName { get; set; }
        public string NumOfDebtorsOnDocument { get; set; }
        public string DataEntryOperatorId { get; set; }
        public Nullable<System.DateTime> EffectiveDateTime { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string SourceDocumentTypeId { get; set; }
        public string SourceDocument { get; set; }
        public string SourceCourtTypeId { get; set; }
        public string SourceCourt { get; set; }
        public string SourceCountyId { get; set; }
        public string CCISCountyId { get; set; }
        public string SourceDocumentIndexNumber { get; set; }
        public string CCISCaseIndexNumber { get; set; }
        public string DocumentNumber { get; set; }
        public string SystemGeneratedFilingFee { get; set; }
        public Nullable<System.DateTime> DateOfAccident { get; set; }
        public string DebtorType { get; set; }
        public string DebtorLastName { get; set; }
        public string DebtorFirstName { get; set; }
        public string DebtorMiddleName { get; set; }
        public string DebtorCompanyName { get; set; }
        public string DebtorStreetNumber { get; set; }
        public string DebtorStreetName { get; set; }
        public string DebtorCityState { get; set; }
        public string DebtorZip { get; set; }
        public string DebtorZipExtended { get; set; }
        public string DebtorOccupation { get; set; }
        public string PropertyCounty { get; set; }
        public string PropertyCountyId { get; set; }
        public string PropertyBlock { get; set; }
        public string PropertyLot { get; set; }
        public string BBL { get; set; }
        public string CompressedNameCountyId { get; set; }
        public string CompressedNameEntityType { get; set; }
        public string CompressedName { get; set; }
        public string CreditorType { get; set; }
        public string CreditorLastName { get; set; }
        public string CreditorFirstName { get; set; }
        public string CreditorMiddleName { get; set; }
        public string CreditorCompanyName { get; set; }
        public string CreditorStreetNumber { get; set; }
        public string CreditorStreetName { get; set; }
        public string CreditorCityState { get; set; }
        public string CreditorZip { get; set; }
        public string CreditorZipExtended { get; set; }
        public string AttorneyType { get; set; }
        public string AttorneyLastName { get; set; }
        public string AttorneyFirstName { get; set; }
        public string AttorneyMiddleName { get; set; }
        public string AttorneyFirmName { get; set; }
        public string AttorneyStreetNumber { get; set; }
        public string AttorneyStreetName { get; set; }
        public string AttorneyCityState { get; set; }
        public string AttorneyZip { get; set; }
        public string AttorneyZipExtended { get; set; }
        public string ThirdPartyType { get; set; }
        public string ThirdPartyLastName { get; set; }
        public string ThirdPartyFirstName { get; set; }
        public string ThirdPartyMiddleName { get; set; }
        public string ThirdPartyCompanyName { get; set; }
        public string ThirdPartyStreetNumber { get; set; }
        public string ThirdPartyStreetName { get; set; }
        public string ThirdPartyCityState { get; set; }
        public string ThirdPartyZip { get; set; }
        public string ThirdPartyZipExtended { get; set; }
        public Nullable<double> MoneyAmount { get; set; }
        public string InterimDispositionId0 { get; set; }
        public string InterimDisposition0 { get; set; }
        public string InterimDispositionId1 { get; set; }
        public string InterimDisposition1 { get; set; }
        public string InterimDispositionId2 { get; set; }
        public string InterimDisposition2 { get; set; }
        public string InterimDispositionId3 { get; set; }
        public string InterimDisposition3 { get; set; }
        public string InterimDispositionId4 { get; set; }
        public string InterimDisposition4 { get; set; }
        public string InterimDispositionId5 { get; set; }
        public string InterimDisposition5 { get; set; }
        public string InterimDispositionId6 { get; set; }
        public string InterimDisposition6 { get; set; }
        public string InterimDispositionId7 { get; set; }
        public string InterimDisposition7 { get; set; }
        public string InterimDispositionId8 { get; set; }
        public string InterimDisposition8 { get; set; }
        public string InterimDispositionId9 { get; set; }
        public string InterimDisposition9 { get; set; }
        public Nullable<System.DateTime> SatisfactionDate { get; set; }
        public string SatisfactionType { get; set; }
        public string SheriffExecutionRequired { get; set; }
        public string SatifactionDataEntryOperator { get; set; }
        public string Remarks { get; set; }
    }
}
