//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJudgeReliefSought5NumberSummary
    {
        public string CountyId { get; set; }
        public string JudgeId { get; set; }
        public string Judge { get; set; }
        public string ReliefSought { get; set; }
        public Nullable<int> Instances { get; set; }
        public Nullable<int> MinDays { get; set; }
        public Nullable<int> DaysWithin25Percentile { get; set; }
        public Nullable<int> MedianDays { get; set; }
        public Nullable<int> AvgDays { get; set; }
        public Nullable<int> DaysWithin75Percentile { get; set; }
        public Nullable<int> MaxDays { get; set; }
    }
}
