//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMotionExpanded
    {
        public string CountyId { get; set; }
        public string CaseIndexNumber { get; set; }
        public string SeqNumber { get; set; }
        public Nullable<System.DateTime> DataEntryDate { get; set; }
        public Nullable<System.DateTime> OriginalDate { get; set; }
        public Nullable<System.DateTime> OriginalDateTimeStamp { get; set; }
        public string OriginalCourtPartId { get; set; }
        public string OriginalCourtPart { get; set; }
        public Nullable<System.DateTime> PreviousDate { get; set; }
        public string PreviousCourtPartId { get; set; }
        public string PreviousCourtPart { get; set; }
        public Nullable<int> AdjournmetCounter { get; set; }
        public string ProceedingTypeId { get; set; }
        public string ProceedingType { get; set; }
        public string ReliefSoughtId { get; set; }
        public string ReliefSought { get; set; }
        public string PartyApplyingForMotion { get; set; }
        public string PartyOpposedToMotion { get; set; }
        public Nullable<System.DateTime> DatePapersFiledForApplyingParty { get; set; }
        public Nullable<System.DateTime> DatePapersFiledForOpposingParty { get; set; }
        public Nullable<System.DateTime> DateDecisionOnMotionRendered { get; set; }
        public string DecisionRendered { get; set; }
        public Nullable<System.DateTime> DateOrderSigned { get; set; }
        public string EffectOrDecisionId { get; set; }
        public string EffectOrDecision { get; set; }
        public string AssignedJudgeId { get; set; }
        public string AssignedJudgeName { get; set; }
        public Nullable<System.DateTime> DateCountyClerkNotifiedOfOroder { get; set; }
        public string ConsolidatedIndexNumber { get; set; }
        public string ConsolidatedCalendarNumber { get; set; }
        public string TransferComment { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public string ReferralCourtPartId { get; set; }
        public string ReferralCourtPart { get; set; }
        public Nullable<int> DaysToDecision { get; set; }
        public string ComplexityIndicator { get; set; }
        public Nullable<System.DateTime> DateMotionDecisionDue { get; set; }
        public Nullable<System.DateTime> Date50DayWarning { get; set; }
        public Nullable<System.DateTime> DateAllPapersDue { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public Nullable<System.DateTime> DateBackOfficeReceivedPapers { get; set; }
        public Nullable<System.DateTime> DateJudgeReceivedPapers { get; set; }
        public Nullable<System.DateTime> DateFullySubmitted { get; set; }
        public string MotionPositionFullySubmitted { get; set; }
        public string MovingAttorneyId { get; set; }
        public string MovingAttorneyFirmName { get; set; }
        public string DecisionComment { get; set; }
        public Nullable<System.DateTime> DecisionDataEntryTimeStamp { get; set; }
        public string MultipeReliefFlag { get; set; }
        public string Answer2214Flag { get; set; }
    }
}
