//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCourtsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMotionSummaryByJudgeReliefSought
    {
        public int PKID { get; set; }
        public string CountyId { get; set; }
        public string JudgeId { get; set; }
        public string Judge { get; set; }
        public string ReliefSought { get; set; }
        public Nullable<int> Denied { get; set; }
        public Nullable<int> Granted { get; set; }
        public Nullable<int> Withdrawn { get; set; }
        public Nullable<int> Other { get; set; }
        public Nullable<int> TotalInstances { get; set; }
    }
}
