//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCDOB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public string BIN { get; set; }
        public string BBL { get; set; }
        public string ComplaintNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string InvalidDateEntered { get; set; }
        public string HouseNumber { get; set; }
        public string StreetName { get; set; }
        public string CommunityBoard { get; set; }
        public string SpecialDistrict { get; set; }
        public string ComplaintCategory { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> DispositionDate { get; set; }
        public string InvalidDispositionDate { get; set; }
        public string DispositionCode { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string InvalidInspectionDate { get; set; }
    }
}
