//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCDOB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public string ISNDOBBISVIOLATION { get; set; }
        public string BBL { get; set; }
        public string InvalidBBL { get; set; }
        public string BIN { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string InValidIssueDate { get; set; }
        public string ViolationTypeCode { get; set; }
        public string ViolationNumber { get; set; }
        public string HouseNumber { get; set; }
        public string StreetName { get; set; }
        public Nullable<System.DateTime> DispositionDate { get; set; }
        public string InValidDispositionDate { get; set; }
        public string DispositionComments { get; set; }
        public string DeviceNumber { get; set; }
        public string ViolationDescription { get; set; }
        public string ECBNumber { get; set; }
        public string Number { get; set; }
        public string ViolationCategory { get; set; }
        public string ViolationType { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    }
}
