//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACRISEntities : DbContext
    {
        public ACRISEntities()
            : base("name=ACRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentControlCode> DocumentControlCodes { get; set; }
        public virtual DbSet<MortgageDeedCrossReference> MortgageDeedCrossReferences { get; set; }
        public virtual DbSet<MortgageDeedLot> MortgageDeedLots { get; set; }
        public virtual DbSet<MortgageDeedMaster> MortgageDeedMasters { get; set; }
        public virtual DbSet<MortgageDeedParty> MortgageDeedParties { get; set; }
        public virtual DbSet<MortgageDeedRemark> MortgageDeedRemarks { get; set; }
        public virtual DbSet<PropertyType> PropertyTypes { get; set; }
        public virtual DbSet<UCCCrossReference> UCCCrossReferences { get; set; }
        public virtual DbSet<UCCLot> UCCLots { get; set; }
        public virtual DbSet<UCCMaster> UCCMasters { get; set; }
        public virtual DbSet<UCCParty> UCCParties { get; set; }
        public virtual DbSet<UCCRemark> UCCRemarks { get; set; }
        public virtual DbSet<vwDeedsByBBLE> vwDeedsByBBLEs { get; set; }
        public virtual DbSet<vwDocumentPartiesByBBLE> vwDocumentPartiesByBBLEs { get; set; }
        public virtual DbSet<vwDocumentPartiesByUniqueKey> vwDocumentPartiesByUniqueKeys { get; set; }
        public virtual DbSet<vwDocumentsByBBLE> vwDocumentsByBBLEs { get; set; }
        public virtual DbSet<LatestContractOfSaleorMemorandumofContract> LatestContractOfSaleorMemorandumofContracts { get; set; }
        public virtual DbSet<LatestDeedDocument> LatestDeedDocuments { get; set; }
    
        [DbFunction("ACRISEntities", "tfnGetDocumentParties")]
        public virtual IQueryable<tfnGetDocumentParties_Result> tfnGetDocumentParties(string uniqueKey, string partyType)
        {
            var uniqueKeyParameter = uniqueKey != null ?
                new ObjectParameter("UniqueKey", uniqueKey) :
                new ObjectParameter("UniqueKey", typeof(string));
    
            var partyTypeParameter = partyType != null ?
                new ObjectParameter("PartyType", partyType) :
                new ObjectParameter("PartyType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetDocumentParties_Result>("[ACRISEntities].[tfnGetDocumentParties](@UniqueKey, @PartyType)", uniqueKeyParameter, partyTypeParameter);
        }
    }
}
