//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ACRISEntities : DbContext
    {
        public ACRISEntities()
            : base("name=ACRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LatestContractOfSaleorMemorandumofContract> LatestContractOfSaleorMemorandumofContracts { get; set; }
        public virtual DbSet<LatestDeedDocument> LatestDeedDocuments { get; set; }
        public virtual DbSet<vwDeedsByBBLE> vwDeedsByBBLEs { get; set; }
        public virtual DbSet<vwDocumentPartiesByBBLE> vwDocumentPartiesByBBLEs { get; set; }
        public virtual DbSet<vwDocumentPartiesByUniqueKey> vwDocumentPartiesByUniqueKeys { get; set; }
        public virtual DbSet<vwDocumentsByBBLE> vwDocumentsByBBLEs { get; set; }
        public virtual DbSet<vwMortgageDeedMaster> vwMortgageDeedMasters { get; set; }
        public virtual DbSet<vwSatisfactionAndAssignmentCrossReeferenceRecord> vwSatisfactionAndAssignmentCrossReeferenceRecords { get; set; }
        public virtual DbSet<PropertyNotInAssessment> PropertyNotInAssessments { get; set; }
    
        [DbFunction("ACRISEntities", "tfnGetDocumentParties")]
        public virtual IQueryable<tfnGetDocumentParties_Result> tfnGetDocumentParties(string uniqueKey, string partyType)
        {
            var uniqueKeyParameter = uniqueKey != null ?
                new ObjectParameter("UniqueKey", uniqueKey) :
                new ObjectParameter("UniqueKey", typeof(string));
    
            var partyTypeParameter = partyType != null ?
                new ObjectParameter("PartyType", partyType) :
                new ObjectParameter("PartyType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetDocumentParties_Result>("[ACRISEntities].[tfnGetDocumentParties](@UniqueKey, @PartyType)", uniqueKeyParameter, partyTypeParameter);
        }
    
        [DbFunction("ACRISEntities", "tfnGetDocumentPartiesByKey")]
        public virtual IQueryable<tfnGetDocumentPartiesByKey_Result> tfnGetDocumentPartiesByKey(string key, string partyType)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var partyTypeParameter = partyType != null ?
                new ObjectParameter("PartyType", partyType) :
                new ObjectParameter("PartyType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetDocumentPartiesByKey_Result>("[ACRISEntities].[tfnGetDocumentPartiesByKey](@Key, @PartyType)", keyParameter, partyTypeParameter);
        }
    
        [DbFunction("ACRISEntities", "tfnGetUnsatisfiedMortgages")]
        public virtual IQueryable<tfnGetUnsatisfiedMortgages_Result> tfnGetUnsatisfiedMortgages(string bBLE)
        {
            var bBLEParameter = bBLE != null ?
                new ObjectParameter("BBLE", bBLE) :
                new ObjectParameter("BBLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetUnsatisfiedMortgages_Result>("[ACRISEntities].[tfnGetUnsatisfiedMortgages](@BBLE)", bBLEParameter);
        }
    
        [DbFunction("ACRISEntities", "tfnGetDocuments")]
        public virtual IQueryable<tfnGetDocuments_Result> tfnGetDocuments(string bBLE, string documentType)
        {
            var bBLEParameter = bBLE != null ?
                new ObjectParameter("BBLE", bBLE) :
                new ObjectParameter("BBLE", typeof(string));
    
            var documentTypeParameter = documentType != null ?
                new ObjectParameter("DocumentType", documentType) :
                new ObjectParameter("DocumentType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetDocuments_Result>("[ACRISEntities].[tfnGetDocuments](@BBLE, @DocumentType)", bBLEParameter, documentTypeParameter);
        }
    
        [DbFunction("ACRISEntities", "tfnGetMortgageChain")]
        public virtual IQueryable<tfnGetMortgageChain_Result> tfnGetMortgageChain(string bBLE)
        {
            var bBLEParameter = bBLE != null ?
                new ObjectParameter("BBLE", bBLE) :
                new ObjectParameter("BBLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetMortgageChain_Result>("[ACRISEntities].[tfnGetMortgageChain](@BBLE)", bBLEParameter);
        }
    }
}
