//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentControlCode
    {
        public string RecordType { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTypeDescription { get; set; }
        public string ClassCodeDescription { get; set; }
        public string Party1Type { get; set; }
        public string Party2Type { get; set; }
        public string Party3Type { get; set; }
    }
}
