//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MortgageDeedLot
    {
        public string BBL { get; set; }
        public string UniqueKey { get; set; }
        public string Borough { get; set; }
        public string Block { get; set; }
        public string Lot { get; set; }
        public string Easement { get; set; }
        public string PartialLot { get; set; }
        public string AirRights { get; set; }
        public string SubterraneanRights { get; set; }
        public string PropertyTypeCode { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string UnitNumber { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
