//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDeedsByBBLE
    {
        public string BBLE { get; set; }
        public string UniqueKey { get; set; }
        public string CRFN { get; set; }
        public string PropertyType { get; set; }
        public string DocumentType { get; set; }
        public string DocumentTypeDescription { get; set; }
        public string DocumentClassCodeDescription { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<decimal> DocumentAmount { get; set; }
        public Nullable<decimal> PercentageOfTransaction { get; set; }
        public Nullable<System.DateTime> DateRecorded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string BoroughOfRecord { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
