//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISecurityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIKeyUser
    {
        public long UserId { get; set; }
        public string APIKey { get; set; }
        public string UserName { get; set; }
    }
}
