//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISecurityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallBack
    {
        public string AccountId { get; set; }
        public string CallType { get; set; }
        public string URL { get; set; }
        public string API { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string APIKey { get; set; }
    }
}
