//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPISecurityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebAPISecurityEntities : DbContext
    {
        public WebAPISecurityEntities()
            : base("name=WebAPISecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIUser> APIUsers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<vwAPIUser> vwAPIUsers { get; set; }
        public virtual DbSet<CallBack> CallBacks { get; set; }
    }
}
