//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCDOF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NYCDOFEntities : DbContext
    {
        public NYCDOFEntities()
            : base("name=NYCDOFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaxLienSold> TaxLienSolds { get; set; }
    
        [DbFunction("NYCDOFEntities", "tfnGetGeneralPropertyInformation")]
        public virtual IQueryable<tfnGetGeneralPropertyInformation_Result> tfnGetGeneralPropertyInformation(string bBLE)
        {
            var bBLEParameter = bBLE != null ?
                new ObjectParameter("BBLE", bBLE) :
                new ObjectParameter("BBLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfnGetGeneralPropertyInformation_Result>("[NYCDOFEntities].[tfnGetGeneralPropertyInformation](@BBLE)", bBLEParameter);
        }
    }
}
