//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCDOF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTaxLien
    {
        public string BBL { get; set; }
        public int TaxLienSaleList { get; set; }
        public int TaxLienSold { get; set; }
        public int TaxLienCertificate { get; set; }
        public Nullable<bool> IsWaterDebtOnly { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Property { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> ERP { get; set; }
        public Nullable<decimal> Environmental { get; set; }
        public Nullable<decimal> CIS { get; set; }
        public Nullable<decimal> NoticingFees { get; set; }
        public Nullable<decimal> Surchages { get; set; }
        public Nullable<decimal> LienTotal { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> DOFInterestRate { get; set; }
        public Nullable<decimal> DEPInterestRate { get; set; }
    }
}
