//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCVNL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECBViolationsSummaryByAgency
    {
        public string BBL { get; set; }
        public string IssuingAgency { get; set; }
        public Nullable<int> Open { get; set; }
        public Nullable<int> Closed { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
    }
}
