//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCVNL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiAgencyViolation
    {
        public string TicketNumber { get; set; }
        public Nullable<System.DateTime> ViolationDate { get; set; }
        public string ViolationTime { get; set; }
        public string IssuingAgency { get; set; }
        public string RespondentName { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public string BBL { get; set; }
        public string ViolationLocationHouseNumber { get; set; }
        public string ViolationLocationStreetNumber { get; set; }
        public string ViolationLocationFloor { get; set; }
        public string ViolationLocationCity { get; set; }
        public string ViolationLocationZipCode { get; set; }
        public string ViolationLocationStateName { get; set; }
        public string RespondentAddressBorough { get; set; }
        public string RespondentAddressHouseNumber { get; set; }
        public string RespondentAddressStreetName { get; set; }
        public string RespondentAddressCity { get; set; }
        public string RespondentAddressZipCode { get; set; }
        public string RespondentAddressStateName { get; set; }
        public string HearingStatus { get; set; }
        public string HearingResult { get; set; }
        public string ScheduledHearingLocation { get; set; }
        public Nullable<System.DateTime> HearingDate { get; set; }
        public string HearingTime { get; set; }
        public string DecisionLocation { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<decimal> TotalViolationAmount { get; set; }
        public string ViolationDetails { get; set; }
        public Nullable<System.DateTime> JudgementDocketedDate { get; set; }
        public string RespondentAddressFacilityNumber { get; set; }
        public Nullable<decimal> PenaltyImposed { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> AdditionalPenaltiesLateFees { get; set; }
        public string ComplianceStatus { get; set; }
        public string ViolationDescription { get; set; }
        public string Charge1Code { get; set; }
        public string Charge1Section { get; set; }
        public string Charge1Description { get; set; }
        public string Charge1InfractionAmount { get; set; }
        public string Charge2Code { get; set; }
        public string Charge2Section { get; set; }
        public string Charge2Description { get; set; }
        public string Charge2InfractionAmount { get; set; }
        public string Charge3Code { get; set; }
        public string Charge3Section { get; set; }
        public string Charge3Description { get; set; }
        public string Charge3InfractionAmount { get; set; }
        public string Charge4Code { get; set; }
        public string Charge4Section { get; set; }
        public string Charge4Description { get; set; }
        public string Charge4InfractionAmount { get; set; }
        public string Charge5Code { get; set; }
        public string Charge5Section { get; set; }
        public string Charge5Description { get; set; }
        public string Charge5InfractionAmount { get; set; }
        public string Charge6Code { get; set; }
        public string Charge6Section { get; set; }
        public string Charge6Description { get; set; }
        public string Charge6InfractionAmount { get; set; }
        public string Charge7Code { get; set; }
        public string Charge7Section { get; set; }
        public string Charge7Description { get; set; }
        public string Charge7InfractionAmount { get; set; }
        public string Charge8Code { get; set; }
        public string Charge8Section { get; set; }
        public string Charge8Description { get; set; }
        public string Charge8InfractionAmount { get; set; }
        public string Charge9Code { get; set; }
        public string Charge9Section { get; set; }
        public string Charge9Description { get; set; }
        public string Charge9InfractionAmount { get; set; }
        public string Charge10Code { get; set; }
        public string Charge10Section { get; set; }
        public string Charge10Description { get; set; }
        public string Charge10InfractionAmount { get; set; }
    }
}
