//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCVNL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NYCVNLEntities : DbContext
    {
        public NYCVNLEntities()
            : base("name=NYCVNLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ECBViolationsSummary> ECBViolationsSummaries { get; set; }
        public virtual DbSet<ECBViolationsSummaryByAgency> ECBViolationsSummaryByAgencies { get; set; }
        public virtual DbSet<MultiAgencyViolation> MultiAgencyViolations { get; set; }
    }
}
