//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public string BBLE { get; set; }
        public Nullable<double> Boro { get; set; }
        public Nullable<double> Block { get; set; }
        public Nullable<double> Lot { get; set; }
        public string Easement { get; set; }
        public double AssessmentYear { get; set; }
        public Nullable<double> CurrentTotalMarketValueLand { get; set; }
        public Nullable<double> CurrentTotalMarketValue { get; set; }
        public Nullable<double> NewTotalMarketValueLand { get; set; }
        public Nullable<double> NewTotalMarketValue { get; set; }
        public string BuildingClass { get; set; }
        public string OwnerName { get; set; }
        public string StreetNumberLow { get; set; }
        public string StreetNumberHigh { get; set; }
        public string IsStreetNumberRange { get; set; }
        public string StreetName { get; set; }
        public Nullable<double> Zip { get; set; }
        public Nullable<double> TotalUnits { get; set; }
        public Nullable<double> ResidentialUnits { get; set; }
        public Nullable<double> LotFrontage { get; set; }
        public Nullable<double> LotDepth { get; set; }
        public Nullable<double> LotArea { get; set; }
        public string IsIrregularLot { get; set; }
        public Nullable<double> BuildingFrontage { get; set; }
        public Nullable<double> BuildingDepth { get; set; }
        public string IsBuildingIrregularShaped { get; set; }
        public string ExtensionType { get; set; }
        public Nullable<double> Stories { get; set; }
        public string CornerLotInformation { get; set; }
        public Nullable<double> LandArea { get; set; }
        public Nullable<double> BuildingGrossArea { get; set; }
        public string ZoningCode { get; set; }
        public Nullable<double> YearBuilt { get; set; }
        public Nullable<double> EndYearBuilt { get; set; }
        public string PriorYearAssessedValueLimited { get; set; }
        public string ParcelValuesAreReflectedInAnotherLot { get; set; }
        public Nullable<double> CondoIdentificationNumber { get; set; }
        public string IsCondoCommercialOrResidential { get; set; }
        public string Suffix1SequenceNumber { get; set; }
        public string LandPercentOfCommonInterestInTheEntireCondo { get; set; }
        public Nullable<double> FinalActualAssessedLandValue { get; set; }
        public Nullable<double> FinalActualAssessedTotalValue { get; set; }
        public Nullable<double> FinalActualExemptLandValue { get; set; }
        public Nullable<double> FinalActualExemptTotalValue { get; set; }
        public int IsTentative { get; set; }
        public string TaxClass { get; set; }
        public string OldTaxClass { get; set; }
        public string AssessedValueLimited { get; set; }
        public Nullable<double> NumberOfBuildingsOnLot { get; set; }
        public string RecordType { get; set; }
        public string NewLot { get; set; }
        public string LotWillBeDropped { get; set; }
        public string BuildingInProgress { get; set; }
        public string BuildingPercentOfCommonInterestInTheEntireCondo { get; set; }
        public string ApartmentNumberForCondominiumProperties { get; set; }
        public Nullable<double> COOPidentificationNumber { get; set; }
        public string ExemptionIndicatorFlags { get; set; }
        public Nullable<double> ExemptionsCount { get; set; }
        public string SchoolDistrict { get; set; }
        public Nullable<decimal> CommunityDistrict { get; set; }
        public string NeighborhoodName { get; set; }
        public string NTACode { get; set; }
        public Nullable<decimal> East { get; set; }
        public Nullable<decimal> North { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public string CoordinatesSource { get; set; }
        public Nullable<double> BuildingGrossAreaCalculated { get; set; }
        public Nullable<decimal> GarageArea { get; set; }
    }
}
