//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMAComparable
    {
        public long CMARunId { get; set; }
        public string ComparableBBL { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual CMARun CMARun { get; set; }
    }
}
