//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMARun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMARun()
        {
            this.CMAComparables = new HashSet<CMAComparable>();
        }
    
        public long CMARunId { get; set; }
        public string UserName { get; set; }
        public string BBL { get; set; }
        public System.DateTime RunDateTime { get; set; }
        public int CMAType { get; set; }
        public string AlgorithmType { get; set; }
        public Nullable<int> RunType { get; set; }
        public Nullable<int> MonthsOffset { get; set; }
        public Nullable<int> GLAHiPercentage { get; set; }
        public Nullable<int> GLALoPercentage { get; set; }
        public Nullable<int> LAHiPercentage { get; set; }
        public Nullable<int> LALoPercentage { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<int> BuildingClassMatch { get; set; }
        public Nullable<decimal> MinSalePrice { get; set; }
        public Nullable<decimal> MaxSalePrice { get; set; }
        public Nullable<int> BuildingFrontageHiRange { get; set; }
        public Nullable<int> BuildingFrontageLoRange { get; set; }
        public Nullable<int> BuildingDepthHiRange { get; set; }
        public Nullable<int> BuildingDepthLoiRange { get; set; }
        public Nullable<int> LotFrontageHiRange { get; set; }
        public Nullable<int> LotFrontageLoRange { get; set; }
        public Nullable<int> LotDepthHiRange { get; set; }
        public Nullable<int> LotDepthLoRange { get; set; }
        public Nullable<bool> SameNeighborhood { get; set; }
        public Nullable<bool> SameSchoolDistrict { get; set; }
        public Nullable<bool> SameZip { get; set; }
        public Nullable<bool> SameStreet { get; set; }
        public Nullable<bool> SameBlock { get; set; }
        public Nullable<bool> IsNotIntraFamily { get; set; }
        public Nullable<bool> BuyerIsCompany { get; set; }
        public Nullable<bool> SellerIsCompany { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CMAComparable> CMAComparables { get; set; }
    }
}
