//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePriceStatisticsByMonthByNeighborhoodMeanSmoothing
    {
        public int PKID { get; set; }
        public string NeighborhoodName { get; set; }
        public string BuildingClass { get; set; }
        public System.DateTime YearMonth { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> Q1Price { get; set; }
        public Nullable<decimal> MedianPrice { get; set; }
        public Nullable<decimal> Q3Price { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
    }
}
