//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCMADB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSuggestedSubjectPrice
    {
        public string SubjectBBL { get; set; }
        public Nullable<double> LowPrice { get; set; }
        public Nullable<double> AVGPrice { get; set; }
        public Nullable<double> MedianPrice { get; set; }
        public Nullable<double> HighPrice { get; set; }
    }
}
